<template>
  <div style="max-width: 400px; margin: 0 auto;">
    <q-form class="column content-stretch q-mb-xl">
      <!-- POLL TITLE AND DESCRIPTION -->
      <h5 class="section-header">
        Title and Description
      </h5>
      <!-- Poll title -->
      <base-input
        v-model="title"
        label="Title"
      />

      <!-- Poll description -->
      <base-input
        v-model="description"
        label="Description"
        type="textarea"
      />

      <!-- POLL OPTIONS -->
      <h5 class="section-header">
        Poll Options
      </h5>

      <!-- Options list -->
      <div
        v-for="(option, index) in options"
        :key="index"
      >
        <base-input
          v-model="options[index]"
          :label="`Option ${index + 1}`"
        />
      </div>

      <!-- Add new option -->
      <div class="text-left">
        <base-button
          color="primary"
          :dense="true"
          label="Add option"
          :flat="true"
          @click="addOption"
        />
      </div>

      <!-- POLL END DATE/TIME -->
      <h5 class="section-header">
        End Date and Time
      </h5>
      <div class="row justify-between">
        <!-- End date -->
        <q-input
          v-model="endDate"
          class="col-auto q-my-sm"
          filled
          label="End date"
          mask="date"
          placeholder="YYYY/MM/DD"
          style="max-width: 190px;"
          :rules="['date']"
        >
          <template v-slot:append>
            <q-icon
              name="fas fa-calendar-alt"
              class="cursor-pointer"
            >
              <q-popup-proxy
                ref="qDateProxy"
                transition-show="scale"
                transition-hide="scale"
              >
                <q-date
                  v-model="endDate"
                  @input="() => $refs.qDateProxy.hide()"
                />
              </q-popup-proxy>
            </q-icon>
          </template>
        </q-input>

        <!-- End time -->
        <q-input
          v-model="endTime"
          class="col-auto q-my-sm"
          filled
          label="End time"
          mask="time"
          placeholder="HH:MM"
          style="max-width: 190px;"
          :rules="['time']"
        >
          <template v-slot:append>
            <q-icon
              name="fas fa-clock"
              class="cursor-pointer"
            >
              <q-popup-proxy
                transition-show="scale"
                transition-hide="scale"
              >
                <q-time
                  v-model="endTime"
                  format24h
                />
              </q-popup-proxy>
            </q-icon>
          </template>
        </q-input>
      </div>

      <div>
        <base-button
          color="primary"
          :full-width="true"
          label="Create"
          @click="createPoll"
        />
      </div>
    </q-form>
  </div>
</template>

<script>
import { mapState } from 'vuex';

export default {
  name: 'TheCreatePollForm',

  data() {
    return {
      // Poll properties
      // id, fancyId, and startDate will be generated by the server
      title: undefined,
      description: undefined,
      endDate: undefined,
      endTime: undefined,
      validEventIds: undefined,
      options: [undefined, undefined], // start with two empty options
    };
  },

  computed: {
    ...mapState({
      userAddress: (state) => state.user.userAddress,
    }),
  },

  mounted() {
    this.startDate = new Date();
  },

  methods: {
    addOption() {
      this.options.push(undefined);
    },

    async createPoll() {
      const pollData = {
        title: this.title,
        description: this.description,
        endDate: this.endDate,
        validEventIds: this.validEventIds,
        pollCreator: this.userAddress,
      };
      console.log('pollData: ', pollData);
    },
  },
};
</script>

<style lang="stylus" scoped>
.section-header {
  color: $secondary
  // margin-top: 1rem
  text-align: left
}
</style>
